/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "outline": "#79747e",
        "on-tertiary-fixed": "#2c0051",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ddb7ff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#7bd6d1",
        "secondary": "#006a67",
        "surface-container-highest": "#e3e2e6",
        "tertiary": "#832ad1",
        "on-secondary-fixed-variant": "#00504d",
        "primary": "#6f42c1",
        "outline-variant": "#cac4d0",
        "primary-fixed": "#ebddff",
        "surface-variant": "#e7e0ec",
        "background": "#fdfcff",
        "inverse-on-surface": "#f1f0f4",
        "on-background": "#1a1c1e",
        "surface": "#fdfcff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#98f2ed",
        "on-primary-fixed": "#250059",
        "on-surface-variant": "#49454f",
        "on-error-container": "#410002",
        "surface-tint": "#6f42c1",
        "on-error": "#ffffff",
        "inverse-primary": "#d3bbff",
        "on-secondary-container": "#00201f",
        "on-primary-fixed-variant": "#5726a8",
        "on-tertiary-container": "#2c0051",
        "on-secondary": "#ffffff",
        "surface-container": "#f3f3f7",
        "surface-dim": "#ded8e1",
        "on-surface": "#1a1c1e",
        "primary-fixed-dim": "#d3bbff",
        "surface-container-high": "#ece6f0",
        "surface-container-low": "#f7f2fa",
        "error-container": "#ffdad6",
        "primary-container": "#e2d0ff",
        "inverse-surface": "#2f3033",
        "secondary-container": "#98f2ed",
        "tertiary-fixed": "#f0dbff",
        "on-tertiary-fixed-variant": "#6900b3",
        "tertiary-container": "#e9cdff",
        "on-primary-container": "#250059",
        "surface-bright": "#fdfcff",
        "on-secondary-fixed": "#00201f",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack-gap": "32px",
        "grid-unit": "8px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }]
      }
    },
  },
  plugins: [],
}
