import React, { useEffect, useState, useRef } from "react";
import { listSubjects, listDocuments, getSubjectNotes, generateQuiz, submitQuiz } from "../api/client";
import { useSearchParams } from "react-router-dom";

const TYPES = [
  { id: "mcq", label: "Multiple Choice" },
  { id: "true_false", label: "True / False" },
  { id: "fill_blank", label: "Fill in the Blank" },
  { id: "short_answer", label: "Short Answer" },
];

export default function ExamCenter() {
  const [subjects, setSubjects] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [subjectId, setSubjectId] = useState("");
  const [selectedDocs, setSelectedDocs] = useState([]);
  const [types, setTypes] = useState(["mcq", "true_false", "fill_blank"]);
  const [numQuestions, setNumQuestions] = useState(8);
  
  const [quiz, setQuiz] = useState(null);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState({});
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [showConfig, setShowConfig] = useState(false); // To toggle generate form
  const [searchParams] = useSearchParams();
  const preselectedTopic = searchParams.get("topic");
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    listSubjects().then((res) => setSubjects(res.data));
  }, []);

  useEffect(() => {
    if (subjectId) {
      Promise.all([
        listDocuments(subjectId),
        getSubjectNotes(subjectId)
      ]).then(([docRes, noteRes]) => {
        const docs = docRes.data.filter(d => d.status === "indexed").map(d => ({ ...d, isNote: false }));
        // Note: multiple notes can share the same topic_id. 
        // We use topic_id as the selection value to send to the backend.
        const notes = noteRes.data.map(n => ({ 
           id: "note_" + n.id, 
           title: n.title, 
           topic_id: n.topic_id, 
           isNote: true 
        }));
        setDocuments([...docs, ...notes]);
      });
    } else {
      setDocuments([]);
    }
  }, [subjectId]);

  const toggleType = (id) => {
    setTypes((prev) => (prev.includes(id) ? prev.filter((t) => t !== id) : [...prev, id]));
  };

  const handleGenerate = async (overrides = {}) => {
    setError("");
    setResult(null);
    setAnswers({});
    setLoading(true);
    try {
      // Split selected items into document_ids and topic_ids
      const realDocIds = [];
      const topicIds = new Set();
      
      for (const id of selectedDocs) {
         if (id.startsWith("note_")) {
            const noteObj = documents.find(d => d.id === id);
            if (noteObj) topicIds.add(noteObj.topic_id);
         } else {
            realDocIds.push(id);
         }
      }
      
      const payload = {
        subject_id: selectedDocs.length === 0 ? subjectId : undefined,
        document_ids: realDocIds,
        topic_ids: Array.from(topicIds),
        question_types: types,
        num_questions: numQuestions,
        ...overrides
      };
      
      const res = await generateQuiz(payload);
      setQuiz(res.data);
      setCurrentQuestionIndex(0);
      setShowConfig(false);
      document.body.style.overflow = 'hidden'; // For cinematic overlay
    } catch (err) {
      console.error(err);
      let errMsg = err?.response?.data?.detail;
      if (typeof errMsg === 'object') {
        errMsg = JSON.stringify(errMsg);
      }
      setError(errMsg || err.message || "An unexpected error occurred while generating the quiz.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (preselectedTopic && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        handleGenerate({ topic_id: preselectedTopic, subject_id: undefined, document_ids: [] });
    }
  }, [preselectedTopic]);

  const closeQuiz = () => {
    setQuiz(null);
    setResult(null);
    document.body.style.overflow = '';
  };

  // Ensure overflow is reset if component unmounts while quiz is active
  useEffect(() => {
    return () => {
      document.body.style.overflow = '';
    };
  }, []);

  const handleSubmit = async () => {
    setLoading(true);
    try {
      const res = await submitQuiz({ quiz_id: quiz.quiz_id, answers });
      setResult(res.data);
    } finally {
      setLoading(false);
    }
  };

  const currentQ = quiz?.questions[currentQuestionIndex];
  const isLastQ = currentQuestionIndex === (quiz?.questions.length || 0) - 1;

  const handleNext = () => {
    if (isLastQ) {
      handleSubmit();
    } else {
      setCurrentQuestionIndex(prev => prev + 1);
    }
  };
  
  const handlePrev = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(prev => prev - 1);
    }
  };

  return (
    <div className="w-full max-w-container-max mx-auto relative z-10 flex flex-col gap-12 mt-4">
      
      {/* Main View (When not in cinematic quiz mode) */}
      <div className={`flex-col gap-12 ${quiz ? 'hidden' : 'flex'}`}>
        
        {/* Header Section */}
        <header className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
          <div className="flex flex-col gap-2">
            <h1 className="font-display-lg text-display-lg text-on-surface">Exam Center</h1>
            <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl">
              Synthesize your knowledge. Generate dynamic assessments based on your second brain architecture or review past performance analytics.
            </p>
          </div>
          <button 
            className="bg-gradient-to-r from-primary to-tertiary text-on-primary px-8 py-4 rounded-full font-label-md text-label-md flex items-center gap-2 shrink-0 shadow-[0_0_20px_rgba(111,66,193,0.3)] hover:scale-105 transition-transform"
            onClick={() => setShowConfig(!showConfig)}
          >
            <span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 1" }}>neurology</span>
            {showConfig ? "Cancel Generation" : "Generate New Quiz"}
          </button>
        </header>

        {/* Configuration Panel */}
        {showConfig && (
          <section className="bg-surface-container/60 backdrop-blur-xl border border-outline-variant/20 rounded-3xl p-8 shadow-lg">
             <h2 className="font-headline-md text-headline-md text-on-surface mb-6 flex items-center gap-2">
                <span className="material-symbols-outlined text-primary">tune</span>
                Configure Assessment
             </h2>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
               <div className="space-y-6">
                  <div>
                    <label className="font-label-md text-label-md text-on-surface-variant mb-2 block">Subject</label>
                    <select 
                      className="w-full bg-surface-container-high/50 border border-outline-variant/20 text-on-surface rounded-xl px-4 py-3 focus:outline-none focus:border-primary/50" 
                      value={subjectId}
                      onChange={(e) => { setSubjectId(e.target.value); setSelectedDocs([]); }}
                    >
                      <option value="">Select subject...</option>
                      {subjects.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
                    </select>
                  </div>
                  
                  <div>
                    <label className="font-label-md text-label-md text-on-surface-variant mb-2 block">Number of Questions</label>
                    <input 
                      type="number" 
                      min={3} 
                      max={25} 
                      className="w-full bg-surface-container-high/50 border border-outline-variant/20 text-on-surface rounded-xl px-4 py-3 focus:outline-none focus:border-primary/50"
                      value={numQuestions} 
                      onChange={(e) => setNumQuestions(Number(e.target.value))} 
                    />
                  </div>

                  <div>
                    <label className="font-label-md text-label-md text-on-surface-variant mb-3 block">Question Types</label>
                    <div className="flex gap-3 flex-wrap">
                      {TYPES.map((t) => (
                        <label key={t.id} className={`flex items-center gap-2 text-sm px-4 py-2 rounded-full cursor-pointer transition-colors border ${
                          types.includes(t.id) ? 'bg-primary/20 border-primary text-primary' : 'bg-surface-container-high/50 border-outline-variant/30 text-on-surface-variant hover:bg-surface-container-highest'
                        }`}>
                          <input type="checkbox" className="hidden" checked={types.includes(t.id)} onChange={() => toggleType(t.id)} />
                          {t.label}
                        </label>
                      ))}
                    </div>
                  </div>
               </div>

               <div>
                 <label className="font-label-md text-label-md text-on-surface-variant mb-2 block">Scope Documents (Optional)</label>
                 <div className="bg-surface-container-low rounded-xl border border-outline-variant/30 min-h-[160px] p-2 flex flex-col gap-2 max-h-64 overflow-y-auto">
                  {documents.length === 0 ? (
                    <div className="m-auto text-on-surface-variant/50 text-sm font-label-md italic">
                       {!subjectId ? "Select a subject first to view documents." : "No documents or notes found in this subject."}
                    </div>
                  ) : (
                    documents.map((doc) => (
                      <label key={doc.id} className="flex items-center gap-3 p-3 hover:bg-surface-container rounded-lg cursor-pointer transition-colors border border-transparent hover:border-outline-variant/20">
                        <input
                          type="checkbox"
                          className="w-4 h-4 text-primary bg-surface-container-high border-outline rounded focus:ring-primary focus:ring-2"
                          checked={selectedDocs.includes(doc.id)}
                          onChange={(e) => {
                            if (e.target.checked) setSelectedDocs((prev) => [...prev, doc.id]);
                            else setSelectedDocs((prev) => prev.filter((id) => id !== doc.id));
                          }}
                        />
                        <span className="material-symbols-outlined text-on-surface-variant/70 text-lg">
                           {doc.isNote ? "edit_note" : "description"}
                        </span>
                        <span className="text-on-surface text-sm font-body-md truncate">{doc.title}</span>
                        {doc.isNote && (
                          <span className="ml-auto text-[10px] font-label-md bg-tertiary/10 text-tertiary px-2 py-0.5 rounded-full border border-tertiary/20">
                            NOTE
                          </span>
                        )}
                      </label>
                    ))
                  )}
                </div>
               </div>
             </div>
             
             {error && <div className="mt-6 p-4 bg-error/10 border border-error/20 rounded-xl text-error text-sm">{error}</div>}
             
             <div className="mt-8 flex justify-end">
               <button 
                 onClick={() => handleGenerate()} 
                 disabled={!subjectId || loading || types.length === 0}
                 className="bg-secondary text-on-secondary font-label-md text-label-md px-8 py-3 rounded-full hover:bg-secondary-fixed transition-colors disabled:opacity-50 disabled:pointer-events-none flex items-center gap-2"
               >
                 {loading ? <><span className="material-symbols-outlined animate-spin">refresh</span> Generating...</> : "Start Assessment"}
               </button>
             </div>
          </section>
        )}

        {/* Empty State / placeholder for recent assessments */}
        {!showConfig && (
          <section className="flex flex-col items-center justify-center py-20 opacity-70">
             <div className="w-24 h-24 bg-surface-container-highest rounded-full flex items-center justify-center mb-6">
                <span className="material-symbols-outlined text-5xl text-outline-variant">history</span>
             </div>
             <h2 className="font-headline-md text-headline-md text-on-surface mb-2">No Recent Assessments</h2>
             <p className="text-on-surface-variant max-w-md text-center">Click "Generate New Quiz" above to create a custom assessment based on your materials.</p>
          </section>
        )}
      </div>


      {/* Active Quiz Mode (Cinematic Overlay) */}
      {quiz && (
        <div className="fixed inset-0 z-[100] bg-background flex flex-col">
          {/* Subtle Animated BG */}
          <div className="absolute inset-0 opacity-30 pointer-events-none" style={{ backgroundImage: "radial-gradient(circle at 50% 50%, rgba(111, 66, 193, 0.1) 0%, transparent 70%)" }}></div>
          
          {/* Header */}
          <header className="h-20 px-4 md:px-8 flex justify-between items-center border-b border-outline-variant/10 bg-surface-container/30 backdrop-blur-md z-10">
            <div className="flex items-center gap-4">
              <button className="text-on-surface-variant hover:text-white transition-colors flex items-center justify-center w-10 h-10 rounded-full bg-surface-container hover:bg-surface-bright" onClick={closeQuiz}>
                <span className="material-symbols-outlined">close</span>
              </button>
              <div className="flex flex-col">
                <span className="font-label-md text-label-md text-secondary text-[10px] md:text-xs uppercase tracking-wider">{result ? 'Assessment Complete' : 'Active Assessment'}</span>
                <span className="font-body-md text-sm md:text-base text-on-surface font-semibold">{quiz.title}</span>
              </div>
            </div>
            
            {!result && (
              <div className="flex items-center gap-6">
                <div className="w-32 h-2 bg-surface-container-highest rounded-full overflow-hidden hidden md:block">
                  <div className="bg-gradient-to-r from-primary to-tertiary h-full rounded-full transition-all duration-500" style={{ width: `${((currentQuestionIndex + 1) / quiz.questions.length) * 100}%` }}></div>
                </div>
                <span className="font-label-md text-label-md text-on-surface">
                  {currentQuestionIndex + 1} / {quiz.questions.length}
                </span>
              </div>
            )}
          </header>

          {/* Canvas */}
          <div className={`flex-1 overflow-y-auto flex flex-col items-center p-6 md:p-12 relative z-10 ${!result ? 'justify-start md:justify-center' : 'justify-start'}`}>
            
            {!result ? (
              /* Question View */
              <div className="max-w-4xl w-full flex flex-col gap-8 md:gap-12 fade-in">
                <div className="text-center">
                  <span className="font-label-md text-label-md text-secondary mb-4 block tracking-widest uppercase">
                    {currentQ?.type.replace('_', ' ')}
                  </span>
                  <h2 className="font-display-lg text-2xl md:text-4xl text-on-surface leading-tight font-light">
                    {currentQ?.question}
                  </h2>
                </div>

                {/* Interactive Answer Area */}
                <div className="w-full max-w-3xl mx-auto mt-4 md:mt-8">
                  {currentQ?.type === "mcq" && (
                    <div className="grid grid-cols-1 gap-4">
                      {currentQ.options.map((opt, i) => {
                        const isSelected = answers[currentQ.id] === opt;
                        return (
                          <div 
                            key={opt}
                            onClick={() => setAnswers(prev => ({ ...prev, [currentQ.id]: opt }))}
                            className={`bg-surface-container/60 backdrop-blur-md rounded-2xl p-4 md:p-6 flex gap-4 items-center cursor-pointer border transition-all duration-200 ${
                              isSelected ? 'border-secondary bg-secondary/10 shadow-[0_0_15px_rgba(123,214,209,0.2)]' : 'border-outline-variant/20 hover:border-white/30 hover:bg-surface-container-highest'
                            }`}
                          >
                            <div className={`w-8 h-8 rounded-full border flex items-center justify-center shrink-0 font-label-md ${
                              isSelected ? 'bg-secondary border-transparent text-background' : 'border-outline-variant/30 text-on-surface-variant'
                            }`}>
                              {String.fromCharCode(65 + i)}
                            </div>
                            <p className="font-body-lg text-sm md:text-lg text-on-surface">{opt}</p>
                          </div>
                        );
                      })}
                    </div>
                  )}

                  {currentQ?.type === "true_false" && (
                    <div className="grid grid-cols-2 gap-4">
                      {['True', 'False'].map((opt) => {
                        const val = opt === 'True';
                        const isSelected = answers[currentQ.id] === val;
                        return (
                          <div 
                            key={opt}
                            onClick={() => setAnswers(prev => ({ ...prev, [currentQ.id]: val }))}
                            className={`bg-surface-container/60 backdrop-blur-md rounded-2xl p-6 md:p-8 flex justify-center items-center cursor-pointer border transition-all duration-200 ${
                              isSelected ? 'border-secondary bg-secondary/10 shadow-[0_0_15px_rgba(123,214,209,0.2)]' : 'border-outline-variant/20 hover:border-white/30 hover:bg-surface-container-highest'
                            }`}
                          >
                            <p className="font-display-lg text-2xl md:text-3xl text-on-surface">{opt}</p>
                          </div>
                        );
                      })}
                    </div>
                  )}

                  {(currentQ?.type === "fill_blank" || currentQ?.type === "short_answer") && (
                    <div className="w-full">
                      <textarea 
                        className="w-full bg-surface-container/60 backdrop-blur-md border border-outline-variant/30 text-on-surface text-lg md:text-xl rounded-3xl p-6 focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary/50 min-h-[150px] shadow-inner"
                        placeholder="Type your answer here..."
                        value={answers[currentQ.id] || ''}
                        onChange={(e) => setAnswers(prev => ({ ...prev, [currentQ.id]: e.target.value }))}
                      />
                    </div>
                  )}
                </div>
              </div>
            ) : (
              /* Results View */
              <div className="max-w-5xl w-full flex flex-col gap-12 pb-20 fade-in">
                 <div className="text-center">
                    <p className="text-6xl md:text-8xl font-display-lg font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary mb-4">
                      {result.score}%
                    </p>
                    <p className="font-body-lg text-lg text-on-surface-variant max-w-2xl mx-auto">{result.recommendation}</p>
                 </div>

                 <div className="space-y-6 mt-8">
                   <h3 className="font-headline-md text-xl text-on-surface border-b border-outline-variant/20 pb-4">Detailed Review</h3>
                   {result.detailed_results?.map((r, i) => (
                      <div key={r.id} className={`bg-surface-container/40 backdrop-blur-md border rounded-2xl p-6 ${
                         r.is_correct === true ? 'border-secondary/30' : r.is_correct === false ? 'border-error/30' : 'border-outline-variant/20'
                      }`}>
                         <p className="font-body-lg text-base md:text-lg text-on-surface mb-6">
                           <span className="text-outline-variant font-mono mr-2">{i + 1}.</span> {r.question}
                         </p>
                         
                         <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                           <div className="bg-surface-container-highest/30 p-4 rounded-xl">
                             <p className="text-xs font-label-md text-on-surface-variant uppercase tracking-wider mb-2">Your Answer</p>
                             <div className="flex items-start gap-2">
                               {r.is_correct === true ? <span className="material-symbols-outlined text-secondary mt-0.5 text-[20px]">check_circle</span> : 
                                r.is_correct === false ? <span className="material-symbols-outlined text-error mt-0.5 text-[20px]">cancel</span> : 
                                null}
                               <p className={`text-base ${r.is_correct === true ? 'text-secondary' : r.is_correct === false ? 'text-error' : 'text-on-surface'}`}>
                                 {r.user_answer !== undefined && r.user_answer !== null && r.user_answer !== "" ? String(r.user_answer) : <span className="italic text-outline">Skipped</span>}
                               </p>
                             </div>
                           </div>
                           <div className="bg-primary/5 border border-primary/10 p-4 rounded-xl">
                             <p className="text-xs font-label-md text-primary uppercase tracking-wider mb-2">Correct Answer</p>
                             <p className="text-base text-on-surface">{String(r.correct_answer)}</p>
                           </div>
                         </div>

                         <div className="bg-surface-container-highest/50 border border-outline-variant/10 p-4 rounded-xl flex gap-3 items-start">
                            <span className="material-symbols-outlined text-tertiary text-[20px]">lightbulb</span>
                            <p className="text-sm text-on-surface-variant leading-relaxed">
                               {r.explanation}
                            </p>
                         </div>
                      </div>
                   ))}
                 </div>
              </div>
            )}
            
          </div>

          {/* Footer Actions (Only for taking quiz) */}
          {!result && (
            <footer className="h-20 md:h-24 px-4 md:px-8 flex justify-between items-center bg-surface-container/30 backdrop-blur-md z-10 border-t border-outline-variant/10">
              <button 
                onClick={handlePrev}
                disabled={currentQuestionIndex === 0}
                className="px-6 py-3 rounded-full border border-outline-variant/30 text-on-surface font-label-md text-sm md:text-base hover:bg-surface-container-highest transition-colors disabled:opacity-30"
              >
                Previous
              </button>
              
              <button 
                onClick={handleNext}
                disabled={loading}
                className={`px-8 py-3 rounded-full font-label-md text-sm md:text-base transition-all duration-300 flex items-center gap-2 ${
                  loading 
                    ? 'bg-surface-container-highest text-on-surface-variant cursor-not-allowed' 
                    : 'bg-gradient-to-r from-primary to-tertiary text-on-primary hover:scale-105 shadow-[0_0_15px_rgba(111,66,193,0.4)] cursor-pointer'
                }`}
              >
                {loading ? (
                   <><span className="material-symbols-outlined animate-spin text-[18px]">refresh</span> Processing...</>
                ) : (
                   isLastQ ? 'Submit Assessment' : 'Next Question'
                )}
              </button>
            </footer>
          )}
        </div>
      )}
    </div>
  );
}
